pipeline:
  apply:
    volumes:
      - /home/jeefy/.kube/config:/root/.kube/config
    image: lachlanevenson/k8s-kubectl:v1.9.2
    commands:
      - kubectl get pods
      - ./apply.sh
services:
  docker:
    image: docker:dind
    command: [ "--storage-driver=vfs", "--tls=false" ]
    privileged: true
