apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    io.kompose.service: emby
  name: emby
spec:
  ports:
  - name: "8096"
    port: 8096
    targetPort: 8096
  - name: "8920"
    port: 8920
    targetPort: 8920
  - name: "7359"
    port: 7359
    protocol: UDP
    targetPort: 7359
  - name: "1900"
    port: 1900
    protocol: UDP
    targetPort: 1900
  selector:
    io.kompose.service: emby
status:
  loadBalancer: {}
