apiVersion: v1
data:
  setupVars.conf: |
    IPV4_ADDRESS=192.168.2.130
    IPV6_ADDRESS=
    WEBPASSWORD=4ca12137cb06f45dcb94ff6ecf659038945af016f9344233324f1c4a3fa6f39c
    PIHOLE_DNS_1=8.8.8.8
    PIHOLE_DNS_2=8.8.4.4
    PIHOLE_INTERFACE=eth0
    # kanachan
kind: ConfigMap
metadata:
  creationTimestamp: 2018-01-27T15:34:34Z
  name: pihole-setupvars
  namespace: default
  resourceVersion: "405545"
  selfLink: /api/v1/namespaces/default/configmaps/pihole-setupvars
  uid: 93b629ad-0377-11e8-a448-74d02b334d5d
