apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    io.kompose.service: pihole
  name: pihole
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pihole
    spec:
      containers:
      - env:
        - name: PROXY_LOCATION
          value: pihole
        - name: ServerIP
          value: 192.168.2.130
        image: diginc/pi-hole:latest
        imagePullPolicy: IfNotPresent
        name: pihole
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/pihole/
          name: nfs-pihole
          subPath: etc
        - mountPath: /etc/pihole/
          name: cm-pihole-setupvars
        - mountPath: /etc/dnsmasq.d/
          name: cm-pihole-dnsmasq
        - mountPath: /var/log/pihole.log
          name: nfs-pihole
          mountPath: pihole.log
      restartPolicy: Always
      volumes:
      - name: nfs-pihole
        persistentVolumeClaim:
          claimName: nfs-pihole
      - name: cm-pihole-dnsmasq
        configMap:
          name: pihole-dnsmasq
      - name: cm-pihole-setupvars
        configMap:
          name: pihole-setupvars
          items:
          - key: setupVars.conf
            path: setupVars.conf
status: {}
