apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    io.kompose.service: sickrage
  name: sickrage
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sickrage
    spec:
      containers:
      - env:
        - name: VIRTUAL_HOST
          value: tv.chocobo
        image: timhaak/sickrage
        name: sickrage
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: nfs-data
          subPath: sickrage
        - mountPath: /data
          name: nfs-archives
          subPath: TV Shows
        - mountPath: /downloads
          name: nfs-archives
          subPath: Incoming
      restartPolicy: Always
      volumes:
      - name: nfs-data
        persistentVolumeClaim:
          claimName: nfs-data
      - name: nfs-archives
        persistentVolumeClaim:
          claimName: nfs-archives
status: {}
