apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-archives-prometheus-server
  annotations:
    volume.beta.kubernetes.io/mount-options: vers=4
  labels:
    name: nfs-archives-prometheus-server
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.130
    path: "/archives/Services/prometheus"
