apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-cacher-archives
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  selector: 
    matchLabels: 
      name: nfs-cacher-archives
