apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-cacher-archives
  annotations:
    volume.beta.kubernetes.io/mount-options: vers=4
spec:
  capacity:
    storage: 1Ti 
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.130
    path: "/archives/Incoming/cache"
