apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-archives-grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: nfs-archives-grafana
