apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-archives-grafana
  annotations:
    volume.beta.kubernetes.io/mount-options: vers=4
  labels:
    name: nfs-archives-grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.2.130
    path: "/archives/Services/grafana"
