apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-cacher-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  selector: 
    matchLabels: 
      name: nfs-cacher-data
