apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/mount-options: vers=4
  labels:
    name: nfs-archives-prometheus-server
  name: nfs-archives-prometheus-server
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: /archives/Services/prometheus/server
    server: 192.168.2.130
  persistentVolumeReclaimPolicy: Retain
status:
  phase: Released
