apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data
  annotations:
    volume.beta.kubernetes.io/mount-options: vers=4
spec:
  capacity:
    storage: 50Gi 
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.130
    path: "/data"
