apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-archives-generic
  annotations:
    volume.beta.kubernetes.io/mount-options: vers=4
  labels:
    name: nfs-archives-generic
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.130
    path: "/archives/Services"
