apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-archives-prometheus-alertmanager
  annotations:
    volume.beta.kubernetes.io/mount-options: vers=4
  labels:
    name: nfs-archives-prometheus-alertmanager
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.2.130
    path: "/archives/Services/prometheus/alertmanager"
