apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    io.kompose.service: gogs
  name: gogs
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gogs
    spec:
      containers:
      - image: gogs/gogs
        name: gogs
        ports:
        - containerPort: 22
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: nfs-data
          subPath: gogs
      restartPolicy: Always
      volumes:
      - name: nfs-data
        persistentVolumeClaim:
          claimName: nfs-data
status: {}
